# -*- coding: utf-8 -*-
# GPIO Pin Configurations (BCM Numbering)
DISPLAY_PIN_RS = 25
DISPLAY_PIN_E = 24
DISPLAY_PIN_RW = None
DISPLAY_PIN_DB1 = 23
DISPLAY_PIN_DB2 = 17
DISPLAY_PIN_DB3 = 21
DISPLAY_PIN_DB4 = 22

ROTARY_PIN_A = 0
ROTARY_PIN_B = 1
ROTARY_PIN_BUTTON = 4
